---
- name: Define topology
  hosts: satellite6:capsules
  connection: local
  gather_facts: false

  vars_files:
    - ../tests/FAM/includes/fam_common_vars.yaml

  module_defaults:
    group/theforeman.foreman.foreman:
      server_url: "{{ _server_url }}"
      username: "{{ _username }}"
      password: "{{ _password }}"
      validate_certs: "{{ _validate_certs }}"

  tasks:
    - name: Set default variable values
      ansible.builtin.set_fact:
        organization: "{{ organization | default(sat_org) | default('Default Organization') }}"
        location: "{{ location | default(sat_loc) | default('Default Location') }}"

    ### Organization
    - name: Create organization
      run_once: true
      theforeman.foreman.organization:
        name: "{{ organization }}"
      register: __create_org
      until: __create_org is not failed
      retries: "{{ _api_call_retries }}"
      delay: "{{ _api_call_delay }}"

    ### Locations
    - name: Create location
      theforeman.foreman.location:
        name: "{{ item }}"
        organizations:
          - "{{ organization }}"
      loop: "{{ [location] if location is string else location }}"
      register: __create_location
      until: __create_location is not failed
      retries: "{{ _api_call_retries }}"
      delay: "{{ _api_call_delay }}"

    ### Host location
    - name: Set host location
      theforeman.foreman.host:
        name: "{{ inventory_hostname }}"
        location: "{{ location if location is string else location[0] }}"
        organization: "{{ organization }}"
      register: __set_host_location
      until: __set_host_location is not failed
      retries: "{{ _api_call_retries }}"
      delay: "{{ _api_call_delay }}"

    ### Smart-proxy location
    - name: Get smart-proxy information
      theforeman.foreman.resource_info:
        resource: smart_proxies
        search: "name ~ {{ inventory_hostname }}"
      register: __proxy_info
      until: __proxy_info is not failed
      retries: "{{ _api_call_retries }}"
      delay: "{{ _api_call_delay }}"

    - name: Set smart-proxy location
      theforeman.foreman.smart_proxy:
        name: "{{ item.name }}"
        url: "{{ item.url }}"
        locations: "{{ [location] if location is string else location }}"
        organizations:
          - "{{ organization }}"
      loop: "{{ __proxy_info.resources }}"
      loop_control:
        label: "{{ item.name }}"
      when: __proxy_info.resources | length > 0
      register: __set_proxy_location
      until: __set_proxy_location is not failed
      retries: "{{ _api_call_retries }}"
      delay: "{{ _api_call_delay }}"

    ### Subnets
    - name: "Get subnet from inventory (using private network IPs)"
      ansible.builtin.set_fact:
        subnet: "{{ (private_ip + '/' + private_netmask) | ansible.utils.ipaddr('network/prefix') }}"
        network: "{{ (private_ip + '/' + private_netmask) | ansible.utils.ipaddr('network') }}"
        netmask: "{{ private_netmask }}"
      when:
        - private_ip is defined
        - private_netmask is defined

    - name: "Get subnet from inventory (using public network IPs)"
      ansible.builtin.set_fact:
        subnet: "{{ (public_ip + '/' + public_netmask) | ansible.utils.ipaddr('network/prefix') }}"
        network: "{{ (public_ip + '/' + public_netmask) | ansible.utils.ipaddr('network') }}"
        netmask: "{{ public_netmask }}"
      when:
        - private_ip is not defined
        - private_netmask is not defined
        - public_ip is defined
        - public_netmask is defined

    - name: Create subnet and assign location
      theforeman.foreman.subnet:
        name: "{{ subnet }}"
        network: "{{ network }}"
        mask: "{{ netmask }}"
        ipam: "None"
        organizations:
          - "{{ organization }}"
        locations: "{{ [location] if location is string else location }}"
      when: subnet is defined
      register: __set_subnet
      until: __set_subnet is not failed
      retries: "{{ _api_call_retries }}"
      delay: "{{ _api_call_delay }}"
...
