---
- name: Setup PCP on Satellite
  hosts: satellite6
  tasks:
    - ansible.builtin.include_tasks: tasks/foreman_pcp_with_repos.yaml
      vars:
        foreman_pcp_setup_role: theforeman.operations.metrics
        foreman_metrics_grafana_enabled: false

- name: Setup PCP on Capsules
  hosts: capsules
  tasks:
    - ansible.builtin.include_tasks: tasks/foreman_pcp_with_repos.yaml
      vars:
        foreman_pcp_setup_role: capsule_metrics

- name: Setup PCP on Capsule Load Balancers
  hosts: capsule_lbs
  roles:
    - role: pcp_baseline
