---
roles:
  - name: linux-system-roles.timesync

  - name: linux-system-roles.firewall

  - name: linux-system-roles.network

  - name: linux-system-roles.storage

  - name: rhsm_helper
    src: git+https://github.com/jhutar/ansible-role-rhsm_helper.git
    version: origin/main

  - name: repo_setup
    src: git+https://github.com/jhutar/ansible-role-repo_setup.git
    version: origin/main

  - name: sosreport_gatherer
    src: git+https://github.com/jhutar/ansible-role-sosreport_gatherer.git
    version: origin/main

collections:
  - name: ansible.utils
...
