---
roles:
  - name: linux-system-roles.firewall

  - name: linux-system-roles.network

  - name: linux-system-roles.rhc

  - name: linux-system-roles.storage

  - name: linux-system-roles.timesync

  - name: repo_setup
    src: git+https://github.com/jhutar/ansible-role-repo_setup.git
    version: origin/main

  - name: sosreport_gatherer
    src: git+https://github.com/jhutar/ansible-role-sosreport_gatherer.git
    version: origin/main

collections:
  - name: ansible.posix

  - name: ansible.utils

  - name: community.general

  - name: theforeman.foreman
    version: ">=5.7.0"

  - name: theforeman.operations
...
