---
foremanctl_forge: https://github.com
foremanctl_organization: theforeman
foremanctl_repo: foremanctl

# foremanctl_deployment_type: server

foremanctl_deployer: satellitectl

foremanctl_add_features: []
foremanctl_remove_features: []

foremanctl_proxy_add_features:
  - ansible
foremanctl_proxy_remove_features: []
