---
foremanctl_proxy_auth_bundle_dir: /var/lib/foremanctl/certs/bundles
foremanctl_proxy_auth_bundle_source_path: >-
  {{ foremanctl_proxy_auth_bundle_dir }}/{{ inventory_hostname }}.tar.gz
foremanctl_proxy_auth_bundle_dest_path: "/root/{{ inventory_hostname }}.tar.gz"
