---
  # Following might fail with
  #   msg: Failed to register with 'subscription.rhn.redhat.com': 'RhsmPool' object has no attribute 'PoolId'
  # Should be already fixed these days upstream:
  #   https://github.com/ansible/ansible-modules-core/issues/421
  # So I patched mine Ansible package (ansible-1.9.4-1.fc23.noarch):
  #   # pwd
  #   /usr/lib/python2.7/site-packages/ansible/modules/core
  #   # curl --insecure https://patch-diff.githubusercontent.com/raw/ansible/ansible-modules-core/pull/1204.patch | patch -p 1 --merge
  #   # vim packaging/os/redhat_subscription.py   # had one merge conflict so had to patch it manually
  # - action: redhat_subscription
  #     state=present
  #     username="{{ rhsm_user }}"
  #     password="{{ rhsm_pass }}"
  #     pool="{{ rhsm_pools }}"
  #     autosubscribe=true
  #   register: registration
  #   until: not registration.failed
  #   retries: 5
  #   delay: 10

  - name: "Make sure we have required variables"
    setup:
      gather_subset: "!all"

  ###- name: "Remove registrations"
  ###  command:
  ###    subscription-manager clean
  ###- name: "Remove any preexistent Satellite config"
  ###  yum:
  ###    name: katello-ca-consumer-*
  ###    state: absent

  # Make sure configuration matches hosted servers.
  # Maybe we had the system registered to some satellite before? Cleanup
  - name: "Ensure we don't have any previous registration"
    redhat_subscription:
      state: absent

  - name: "Register the system with RHSM"
    redhat_subscription:
      server_hostname: 'subscription.rhsm.redhat.com'
      server_port: 443
      server_prefix: '/subscription'
      rhsm_baseurl: 'https://cdn.redhat.com'
      rhsm_repo_ca_cert: '/etc/rhsm/ca/redhat-uep.pem'
      username: "{{ rhsm_user }}"
      password: "{{ rhsm_pass }}"
      force_register: true
      pool: "{{ rhsm_pool | regex_escape() }}"
    register: registering
    until: registering.changed
    retries: 30
    delay: 10

  # Make sure only base RHEL repo is attached
  - name: "Disable all RHSM repos and only enable main RHEL7 repo"
    rhsm_repository:
      name: 'rhel-7-server-rpms'
      purge: True
    when: ansible_distribution_major_version == 7 and registering.changed
  - name: "Disable all RHSM repos and only enable main RHEL8 repos"
    rhsm_repository:
      name:
        - 'rhel-8-for-x86_64-baseos-rpms'
        - 'rhel-8-for-x86_64-appstream-rpms'
      purge: True
    when: ansible_distribution_major_version == 8 and registering.changed
...
