---
- hosts: satellite6
  gather_facts: False
  vars:
    - installer_additional_ops: ''
  roles:
    - ../common/roles/scalelab-nic-cleanup
    - ../common/roles/common
    - ../common/roles/remove-home-extend-root
    - ../common/roles/enlarge-arp-table
    - linux-system-roles.timesync
  tasks:
  - name: disable & enable repos
    shell: "{{ item }}"
    with_items:
     - subscription-manager repos --disable "*"
     - subscription-manager repos --enable rhel-7-server-rpms
     - subscription-manager repos --enable rhel-7-server-optional-rpms
     - subscription-manager repos --enable rhel-7-server-extras-rpms
     - yum install -y yum-utils
    when: ansible_distribution == "RedHat"

  - name: settup the server for installation
    shell: |
        yum -y install centos-release-scl
        curl -o /etc/yum.repos.d/satellite.repo http://perf54.perf.lab.eng.bos.redhat.com/pub/mirrors/2020-04-30-Katello_Nightly_Sat68_snap1/satellite.repo

  - name: make a entry of IP & hostname in /etc/hosts file
    lineinfile:
     path: /etc/hosts
     line: '{{ ansible_default_ipv4.address }} {{ ansible_hostname }}'
     create: yes

  - name: install the katello nightly
    shell: yum -y install katello

  - name: configure the katello nightly
    command: foreman-installer --scenario katello --skip-checks-i-know-better --foreman-initial-admin-username {{ sat_user }} --foreman-initial-admin-password {{ sat_pass }} {{ installer_additional_ops }}

  - name: Put SELinux in permissive mode   #workaround for https://projects.theforeman.org/issues/29603
    selinux:
     policy: targeted
     state: permissive

  - name: change the 'pool' setting in database.yml file  #workaround for https://projects.theforeman.org/issues/29370
    replace:
     path: /etc/foreman/database.yml
     regexp: 'pool: 5$'
     replace: 'pool: 30'

  - name: create a file with content  #workaround for https://projects.theforeman.org/issues/29370
    copy:
     dest: /usr/share/foreman/config/initializers/foreman-tasks-db-pool-size.rb
     content: |
             ForemanTasks.dynflow.config.db_pool_size = 30

  - name: restart the foreman service  #workaround for https://projects.theforeman.org/issues/29370
    shell: foreman-maintain service restart
