---
# satperf project settings
satperf_hosts: conf/hosts.ini
satperf_private_key: conf/id_rsa
satperf_log_file: log/satperf.log
satperf_tname: sample_run
satperf_log_file_size: 10000 # in bytes

# Credentials for RHSM (for Satellite and Docker host machines  registration, Capsules are registered into Satellite)
rhsm_user: your_portal_username
rhsm_pass: your_portal_passowd
rhsm_pool: 'Pool you want to consume'

# Skip, Remove home partition and Extend Root partiion.
extend_root_partition: 'true'

# Satellite
sat_version: "6.3"
sat_user: admin
sat_pass: changeme
sat_email: root@localhost
sat_org: Default Organization
sat_orglabel: Default_Organization
sat_orgid: 1
sat_location: Default Location
sat_releasever: "7Server"
sat_repos_sync: 'async'   # Set to 'async' if you want to sync repos with '--async', or to 'sync' if you do not want that option
sat_repos:
  - product: "Red Hat Enterprise Linux Server"
    reposet: "Red Hat Enterprise Linux {{ ansible_distribution_major_version }} Server (RPMs)"
    repo: "Red Hat Enterprise Linux {{ ansible_distribution_major_version }} Server RPMs x86_64 {{ sat_releasever }}"
  - product: "Red Hat Enterprise Linux Server"
    reposet: "Red Hat Enterprise Linux {{ ansible_distribution_major_version }} Server - RH Common (RPMs)"
    repo: "Red Hat Enterprise Linux {{ ansible_distribution_major_version }} Server - RH Common RPMs x86_64 {{ sat_releasever }}"
  - product: "Red Hat Satellite Capsule"
    reposet: "Red Hat Satellite Capsule {{ sat_version }} (for RHEL {{ ansible_distribution_major_version }} Server) (RPMs)"
    repo: "Red Hat Satellite Capsule {{ sat_version }} for RHEL {{ ansible_distribution_major_version }} Server RPMs x86_64"
  - product: "Red Hat Software Collections for RHEL Server"
    reposet: "Red Hat Software Collections RPMs for Red Hat Enterprise Linux {{ ansible_distribution_major_version }} Server"
    repo: "Red Hat Software Collections RPMs for Red Hat Enterprise Linux {{ ansible_distribution_major_version }} Server x86_64 {{ sat_releasever }}"
  - product: "Red Hat Enterprise Linux Server"
    reposet: "Red Hat Enterprise Linux {{ ansible_distribution_major_version }} Server - Optional (RPMs)"
    repo: "Red Hat Enterprise Linux {{ ansible_distribution_major_version }} Server - Optional RPMs x86_64 {{ sat_releasever }}"

# Satellite install options
sat_install_source: cdn   # either 'cdn' or 'repo'
                          #   'cdn' ... configure value of 'sat_cdn_reponame'
                          #   'repo' ... configure value of 'sat_repo_file'
sat_repo_file: ../../../../../conf/sat63.repo
sat_cdn_reponame: 'rhel-{{ ansible_distribution_major_version }}-server-satellite-{{ sat_version }}-rpms'
sat_install_pool: 'Pool you want to use'   # when installing from CDN, this have to contain Satellite and Software Collections
                                           # when installing from custom repository, Software Collections should be enough
# sat_installer_pkg: capsule-installer   # Satellite 6.1
# sat_installer_cmd: katello-installer   # Satellite 6.1
sat_installer_pkg: satellite   # Satellite 6.2 and 6.3
sat_installer_cmd: satellite-installer --scenario satellite   # Satellite 6.2 and 6.3
sat_manifest: ../../../../../conf/manifest.zip

# Katello nightly install options
foreman_repositories_version: nightly
foreman_repository_base: "http://koji.katello.org/releases/yum/foreman-{{ foreman_repositories_version }}/RHEL/{{ ansible_distribution_major_version }}/x86_64/"
foreman_plugin_repository_base: "http://koji.katello.org/releases/yum/foreman-plugins-{{ foreman_repositories_version }}/RHEL/{{ ansible_distribution_major_version }}/x86_64/"
katello_repositories_version: nightly
katello_repositories_pulp_version: 2.15
katello_repositories_pulp_release: stable
epel_repo_installer: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
katello_installer_cmd: foreman-installer --scenario katello
katello_user: admin
katello_password: changeme
katello_ports:
  - 80/tcp
  - 443/tcp
  - 5647/tcp
  - 9090/tcp

# Content for client testing (RHEL repo with erratas and Satellite tools repo)
content_rhel_name: RHEL7 x86_64 Base
content_rhel_label: rhel7-x86_64-base
content_rhel_url: http://repos.example.com/released/RHEL-7/7.2/Server/x86_64/os/
content_sattools_name: Sat Tools
content_sattools_label: sat-x86_64-tools
content_sattools_url: http://repos.example.com/released/SatTools/7Server/x86_64/os/
content_daemonize: daemonize-1.7.7-1.el7.x86_64.rpm
content_puppet_module_author: satperf
content_puppet_module_name: satperftest
content_puppet_module: "{{ content_puppet_module_author }}-{{ content_puppet_module_name }}"
content_puppet_module_file: /tmp/puppet-satperftest.txt
content_puppet_module_file_content: Some important sentence
content_puppet_product: SatPerfPuppetProduct
content_puppet_repo: SatPerfPuppetRepo
content_puppet_env: KT_Default_Organization_Library_SatPerfContentView_2
content_content_view_name: SatPerfContentView
content_hostgroup: "SatperfHostGroup"
content_activationkey: "SatperfActivationKey"
client_domain: "example.com"
client_private_key: "{{ satperf_private_key }}"   # key to access clients (containers)

# Capsule install options
base_capsule_pool: 'Pool you want to consume' # Needs to contain Base RHEL7 repo, which is set via rhsm-satellite, as every manifest may not have 'Employee SKU'.
sat_capsule_pool: 'Pool you want to consume'   # Needs to contain Capsule
capsule_repos_sync: 'async'   # Set to 'async' if you want to sync repos with '--async', or to 'sync' if you do not want that option
capsule_install_source: cdn   # either 'cdn' or 'repo'
                              #   'cdn' ... configure value of 'capsule_cdn_reponame'
                              #   'repo' ... configure value of 'capsule_repo_file'
capsule_repo_file: ../../../../../conf/capsule63.repo
capsule_cdn_reponame: 'rhel-{{ ansible_distribution_major_version }}-server-satellite-capsule-{{ sat_version }}-rpms'
capsule_install_pool: 'Pool you want to use'   # when installing from CDN, this have to contain Capsule
# capsule_installer_pkg: capsule-installer   # Satellite 6.1
# capsule_installer_cmd: katello-installer   # Satellite 6.1
capsule_installer_pkg: satellite-capsule   # Satellite 6.2 and 6.3
capsule_installer_cmd: satellite-installer --scenario capsule   # Satellite 6.2 and 6.3

# Docker hosts
docker_host_register_to: satellite   # from where we should install docker host? Either 'satellite' for your Satellite or anythong else for cdn.redhat.com
docker_host_containers: 50
docker_host_partitioning: kvm
docker_host_storage_driver: devicemapper   # which storage driver should Docker use, "devicemapper" or "overlay"
docker_host_vg: docker   # name of the VG to be used when using Devicemapper direct LVM; when empty, use first VG you find

# Puppet 4 Repos
puppet4_repo: Sat6-CI_Satellite_6_3_Composes_Satellite_6_3_Puppet_4_RHEL7
install_puppet4: True

# Environment
ntp_server: clock.redhat.com

# EPEL
epel_release_rpm: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"

# Monitoring
pbench_enabled: True
pbench_repo_file: "https://copr.fedorainfracloud.org/coprs/ndokos/pbench/repo/epel-{{ ansible_distribution_major_version }}/ndokos-pbench-epel-{{ ansible_distribution_major_version }}.repo"

# Product names to be created
tests_products: perf-gen1 perf-gen2 perf-gen3 perf-gen4 perf-gen5 perf-gen6 perf-gen7 perf-gen8
tests_backup_path: /home/backup

# workload settings
methods:
  repo_count: 5 #Number of repos
  cv_scale: 1 #Content view Scale: True(1), False(0)
  cv_count: 10 #if CVSCALE=true, then  Number of content views
  cv_pub: 10 #number of times content publish
  concurrent: 1 #concurrent (1) or sync (0)

Monitoring:
  # for collectd multi/single-host installations
  # one/all of satellite6:docker-hosts:capsules
  # hosts: satellite6:capsules
  hosts: satellite6

########################################
# Collectd Configuration
########################################
# Interval in seconds
collectd_interval: 10
# Run collectd on specific Satellite-6 nodes:

########################################
# Graphite Configuration
########################################
# Graphite Server gathered as groups['graphite']|first (Collectd -> Graphite server)
# Port Graphite is listening on
graphite_port: 80
# Graphite prefix / Cloud name used both with graphite and grafana dashboards
graphite_prefix: satellite
# Graphite username and password for login on the dashboard
graphite_username: root
graphite_password: password

########################################
# Grafana Dashboarding Configuration
########################################
# Grafana Server gathered as groups['grafana']|first (Can be hosted on the Graphite server)
# Port Grafite is listening on
grafana_host: 127.0.0.1
grafana_port: 3000
# Grafana username and password
grafana_username: admin
grafana_password: admin

#Grafana Panel Mappings
grafana_panels:
  cpu: 1
  memory: 5
  http_cpu: 43
  dynflow_cpu: 44
  smartproxy_cpu: 45
  mongodb_cpu: 46
  passenger_cpu: 47
  postgres_cpu: 48
  pulp_cpu: 49
  puppet_agent_cpu: 50
  qpidd_cpu: 51
  tomcat_cpu: 52
  http_mem: 56
  dynflow_mem: 57
  smartproxy_mem: 58
  mongodb_mem: 59
  passenger_mem: 60
  postgres_mem: 61
  pulp_mem: 62
  puppet_agent_mem: 63
  qpidd_mem: 64
  tomcat_mem: 65
  postgres_db_size: 108
  postgres_connected_clients: 109
  postgres_foreman_op: 113
  postgres_candlepin_op: 114

# If you have some service where you can add results of experiments, set its hostname
recorder_server: ''

# VMs provisioning
vms:
  kvm1.example.com:
    - name: kvm1-vm1
      cpu_count: 4
      mem_size: 16000
      disk: pool=default,size=100,cache=none
      nic_1g_bridge: br1
      nic_1g_mac: RANDOM
      nic_10g_bridge: br0
      nic_10g_mac: RANDOM
      ks: rhel72-vm.ks
      ip: 172.1.1.2
      netmask: 255.0.0.0
      rootpw: password
vms_kss_os: http://repos.example.com/RHEL-7/7.4/Server/x86_64/os/
vms_ssh_key: "{{ lookup('file', '../../conf/id_rsa.pub') }}"
...
