---
- name: Check that provided path is a real file
  ansible.builtin.stat:
    path: "{{ override_images_content_file }}"
  delegate_to: localhost
  register: _override_images_st

- name: Read content from file
  ansible.builtin.slurp:
    src: "{{ override_images_content_file }}"
  delegate_to: localhost
  register: _override_images_content_raw
  when: _override_images_st.stat.exists

- name: Set override content
  ansible.builtin.set_fact:
    _override_images_content: "{{ (_override_images_content_raw.content | b64decode) if _override_images_st.stat.exists else override_images_content_file }}"

- name: Detect append mode (content starts with newline, not ---)
  ansible.builtin.set_fact:
    _override_images_append: "{{ _override_images_content is match('^\n') }}"

- name: Overwrite images.yml (content starts with ---)
  ansible.builtin.copy:
    content: "{{ _override_images_content }}"
    dest: /usr/share/foremanctl/src/vars/images.yml
    mode: '0644'
  when: not _override_images_append

- name: Append to images.yml (content starts with newline)
  ansible.builtin.blockinfile:
    path: /usr/share/foremanctl/src/vars/images.yml
    block: "{{ _override_images_content }}"
    marker: "# {mark} SATPERF OVERRIDE"
  when: _override_images_append

- name: Remove content_file now that its content has been copied
  ansible.builtin.file:
    path: "{{ override_images_content_file }}"
    state: absent
  delegate_to: localhost
  when: _override_images_st.stat.exists
