---
- name: Requirements
  block:
    - name: Foreman
      when:
        - product is defined and product == 'foreman'
      block:
        - name: Assert required Foreman facts
          ansible.builtin.assert:
            that:
              - foreman_version is defined and foreman_version | length > 0
              - katello_version is defined and katello_version | length > 0

    - name: Satellite
      when:
        - product is not defined or product == 'satellite'
      block:
        - name: Setup Satellite repositories
          ansible.builtin.include_role:
            name: repo_setup
          vars:
            sat_version: 'stream'

- name: EL 9
  when:
    - ansible_facts['distribution_major_version'] | int == 9
  block:
    - name: Enable foremanctl COPR
      community.general.copr:
        name: "@theforeman/foremanctl"
        chroot: "rhel-{{ ansible_facts['distribution_major_version'] }}-x86_64"

- name: EL 10
  when:
    - ansible_facts['distribution_major_version'] | int == 10
  block:
    - name: Enable foremanctl COPR
      community.general.copr:
        name: "ekohl/foreman-nightly-staging"
        chroot: "rhel-{{ ansible_facts['distribution_major_version'] }}-x86_64"

- name: Install foremanctl package
  ansible.builtin.dnf:
    name: foremanctl
    state: latest
    # # XXX:
    # disable_gpg_check: true

- name: Use code from git
  when:
    - use_git is defined and use_git | bool
  block:
    - name: Set required variable(s) values
      ansible.builtin.set_fact:
        _foremanctl_organization: "{{ organization | default('theforeman') }}"

    - name: Vanilla git
      when:
        - prs is not defined or prs | length == 0
        - version is not defined or version | length == 0
      block:
        - name: Clone foremanctl git repo # noqa: latest[git]
          ansible.builtin.git:
            repo: "https://github.com/theforeman/foremanctl.git"
            dest: /tmp/foremanctl

    - name: PRs
      when:
        - prs is defined and prs | length > 0
      block:
        - name: Set required variable(s) values
          ansible.builtin.set_fact:
            _foremanctl_prs_list: "{{ prs | split }}"

        - name: Clone foremanctl git repo  # noqa: latest[git]
          ansible.builtin.git:
            repo: "https://github.com/{{ _foremanctl_organization }}/foremanctl.git"
            dest: /tmp/foremanctl
            refspec: '+refs/pull/*:refs/heads/*'
            version: HEAD

        - name: "Apply foremanctl PRs: {{ prs }}"  # noqa: command-instead-of-module
          ansible.builtin.shell:
            cmd: >-
              set -o pipefail

              git fetch origin refs/pull/{{ item }}/head &&
              git format-patch $(git merge-base HEAD FETCH_HEAD)..FETCH_HEAD --stdout |
              git am
            chdir: /tmp/foremanctl
          loop: "{{ _foremanctl_prs_list }}"
          changed_when: true

    - name: Version
      when:
        - version is defined and version | length > 0
      block:
        - name: Clone foremanctl git repo
          ansible.builtin.git:
            repo: "https://github.com/{{ _foremanctl_organization }}/foremanctl.git"
            dest: /tmp/foremanctl
            version: "{{ version }}"

    - name: Move the original src directory
      ansible.builtin.copy:
        src: /usr/share/foremanctl/src/
        dest: /usr/share/foremanctl/src.orig/
        mode: 'preserve'
        remote_src: true

    - name: Remove original src directory
      ansible.builtin.file:
        path: /usr/share/foremanctl/src/
        state: absent

    - name: Copy the src directory from the git clone
      ansible.builtin.copy:
        src: /tmp/foremanctl/src/
        dest: /usr/share/foremanctl/src/
        mode: 'preserve'
        remote_src: true

    # XXX: Hack!!!
    - name: Install foremanctl Ansible collections from src
      when:
        - ansible_facts['distribution_major_version'] | int == 10
      ansible.builtin.command:
        cmd: >-
          ansible-galaxy collection install
          -r /usr/share/foremanctl/src/requirements.yml
          -p /usr/share/foremanctl/collections/ansible_collections
      changed_when: true

- name: Log in to the registry
  containers.podman.podman_login:
    registry: "{{ registry }}"
    username: "{{ registry_username }}"
    password: "{{ registry_password }}"
    authfile: /etc/foreman/registry-auth.json
  when:
    - registry is defined and registry != "quay.io"
    - registry_username is defined and registry_username | length > 0
    - registry_password is defined and registry_password | length > 0

- name: Override images vars file
  ansible.builtin.include_role:
    name: override_images
  when:
    - override_images_content_file is defined and override_images_content_file | length > 0

- name: Set deployer command
  ansible.builtin.set_fact:
    _foremanctl_deployer: foremanctl

- name: Set command line to pull images
  ansible.builtin.set_fact:
    _foremanctl_pull_images_cmd: "{{ _foremanctl_deployer }} pull-images"

- name: Pull images
  block:
    - name: Show command line to pull images
      ansible.builtin.debug:
        msg: "{{ _foremanctl_pull_images_cmd }}"

    - name: Pull images
      ansible.builtin.command:
        cmd: "{{ _foremanctl_pull_images_cmd }}"
      register: _foremanctl_pull_images_cmd_out
      # XXX: Ignore errors in order to be able to show `_foremanctl_pull_images_cmd_out.stdout_lines`
      ignore_errors: true
      changed_when: true

    - name: Show pull images output
      ansible.builtin.debug:
        var: _foremanctl_pull_images_cmd_out.stdout_lines
      failed_when:
        - _foremanctl_pull_images_cmd_out is failed

- name: Set command line to deploy
  ansible.builtin.set_fact:
    _foremanctl_deploy_cmd: "{{ _foremanctl_deployer }} deploy"

- name: Initial deployment
  block:
    - name: Set basic deployment command line
      ansible.builtin.set_fact:
        _foremanctl_initial_deploy_cmd: >-
          {{ _foremanctl_deploy_cmd }}
          --foreman-initial-admin-password {{ password | default('{{ foreman_password }}') }}

    - name: Show deployment command line
      ansible.builtin.debug:
        msg: "{{ _foremanctl_initial_deploy_cmd }}"

    - name: Run deployment
      ansible.builtin.command:
        cmd: "{{ _foremanctl_initial_deploy_cmd }}"
      register: _foremanctl_initial_deploy_cmd_out
      # XXX: Ignore errors in order to be able to show `_foremanctl_initial_deploy_cmd_out.stdout_lines`
      ignore_errors: true
      changed_when: true

    - name: Show deployment output
      ansible.builtin.debug:
        var: _foremanctl_initial_deploy_cmd_out.stdout_lines
      failed_when:
        - _foremanctl_initial_deploy_cmd_out is failed

    - name: Calculate deployment duration
      ansible.builtin.set_fact:
        _foremanctl_duration: >-
          {{ (_foremanctl_initial_deploy_cmd_out.end | to_datetime('%Y-%m-%d %H:%M:%S.%f')).timestamp()
             - (_foremanctl_initial_deploy_cmd_out.start | to_datetime('%Y-%m-%d %H:%M:%S.%f')).timestamp() }}

    - name: Show deployment duration
      ansible.builtin.debug:
        msg: >-
          ForemanctlDeploy {{ _foremanctl_initial_deploy_cmd_out.start }}
          to {{ _foremanctl_initial_deploy_cmd_out.end }}
          taking {{ _foremanctl_duration }} seconds

- name: Add features
  block:
    - name: Add iop to features if enabled
      ansible.builtin.set_fact:
        foremanctl_features: "{{ foremanctl_features + ['iop'] }}"
      when: enable_iop | default(false) | bool

    - name: Foreman
      when:
        - product is defined and product == 'foreman'
      block:
        - name: Setup Foreman repositories for hammer
          ansible.builtin.include_role:
            name: theforeman.operations.foreman_repositories
          vars:
            foreman_repositories_version: nightly
            foreman_repositories_katello_version: nightly
          when: "'hammer' in foremanctl_features"

    - name: Set features deployment command line
      ansible.builtin.set_fact:
        _foremanctl_add_features_cmd: >-
          {{ _foremanctl_deploy_cmd }}
          {{ foremanctl_features | map('regex_replace', '^(.+)$', '--add-feature \1') | join(' ') }}

    - name: Show features deployment command line
      ansible.builtin.debug:
        msg: "{{ _foremanctl_add_features_cmd }}"

    - name: Run features deployment
      ansible.builtin.command:
        cmd: "{{ _foremanctl_add_features_cmd }}"
      register: _foremanctl_add_features_cmd_out
      # XXX: Ignore errors in order to be able to show
      # `_foremanctl_add_features_cmd_out.stdout_lines`
      ignore_errors: true
      changed_when: true

    - name: Show features deployment output
      ansible.builtin.debug:
        var: _foremanctl_add_features_cmd_out.stdout_lines
      failed_when:
        - _foremanctl_add_features_cmd_out is failed

    - name: Foreman
      when:
        - product is defined and product == 'foreman'
      block:
        - name: Disable Foreman repositories
          ansible.builtin.dnf:
            name: foreman-release
            state: absent
          when: "'hammer' in foremanctl_features"
