---
- name: "Assert required facts"
  ansible.builtin.assert:
    that:
      - location is defined
    fail_msg: "'location' must be set on capsule LB hosts"

- name: "Get group name of our location"
  ansible.builtin.set_fact:
    _haproxy_location_groupname: "location_{{ location | lower }}"

- name: "Get capsule names"
  ansible.builtin.set_fact:
    _haproxy_lb_capsules: "{{ groups['capsules'] | intersect(groups[_haproxy_location_groupname]) | sort }}"

- name: Assert location capsules are known
  ansible.builtin.assert:
    that:
      - _haproxy_lb_capsules | length > 0
    fail_msg: >-
      No capsules found for location {{ location }} (group {{ _haproxy_location_groupname }})

- ansible.builtin.include_tasks: ../../tasks/deployment_method/inherit.yaml
  vars:
    _deployment_method_inherit_from: "{{ _haproxy_lb_capsules[0] }}"

- name: "Tune sysctl"
  ansible.posix.sysctl:
    sysctl_file: "/etc/sysctl.d/30-hapee-2.8.conf"
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    reload: True
  loop: "{{ _haproxy_sysctl_config | dict2items }}"

- name: "Install HAProxy"
  ansible.builtin.dnf:
    name: haproxy
    state: latest

- name: "Install policycoreutils-python-utils (`semanage` package)"
  ansible.builtin.dnf:
    name: policycoreutils-python-utils
    state: latest

- name: "Configure SELinux to allow HAProxy to bind any port"
  ansible.posix.seboolean:
    name: haproxy_connect_any
    state: true
    persistent: true

- name: "Create HAProxy systemd override directory"
  ansible.builtin.file:
    path: /etc/systemd/system/haproxy.service.d
    state: directory
    mode: '0755'

- name: "Raise file descriptor limit for HAProxy"
  ansible.builtin.copy:
    dest: /etc/systemd/system/haproxy.service.d/limits.conf
    content: |
      [Service]
      LimitNOFILE=65536
    mode: '0644'
  notify: restart haproxy

- name: "Configure HAproxy"
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: '0644'
  notify: restart haproxy

- name: "Start and enable HAProxy systemd service unit"
  ansible.builtin.systemd_service:
    name: haproxy
    state: started
    enabled: true
